name: Lighthouse CI
on:
  push:
    branches: [ master ]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://www.lucasbrito.com.br
            https://www.lucasbrito.com.br/home
            https://www.lucasbrito.com.br/publications
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage